<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<AssemblyTitle>OLLM</AssemblyTitle>
		<ApplicationIcon>.Images\iconv1.ico</ApplicationIcon>
		<EnableGamingTargetSupport>false</EnableGamingTargetSupport>
		<RepositoryUrl>https://github.com/readydos/Local-LLM-ONNX</RepositoryUrl>
		<PackageTags>llm;ml.net;ml;ai;chat;rag;vector;onnx;local;embed</PackageTags>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<WarningsAsErrors>False</WarningsAsErrors>
		<NoWarn>NU1900</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
		<CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
	</PropertyGroup>

	<PropertyGroup>
		<BuildDateUtc>$([System.DateTime]::UtcNow.ToString("yyyyMMdd"))</BuildDateUtc>
		<BuildTimeUtc>$([System.DateTime]::UtcNow.ToString("HHmmss"))</BuildTimeUtc>
		<BuildTimeMonthUtc>$([System.DateTime]::UtcNow.ToString("MM"))</BuildTimeMonthUtc>
		<BuildTimeSecondsUtc>$([System.DateTime]::UtcNow.ToString("ss"))</BuildTimeSecondsUtc>
		<DynamicVersionPart>$(BuildDateUtc).$(BuildTimeUtc)</DynamicVersionPart>
		<VersionPrefix>1.0</VersionPrefix>
		<Version>$(VersionPrefix).$(BuildTimeMonthUtc).$(BuildTimeSecondsUtc)</Version>
		<AssemblyVersion>$(VersionPrefix).$(BuildTimeMonthUtc).$(BuildTimeSecondsUtc)</AssemblyVersion>
		<FileVersion>$(Version)</FileVersion>
		<InformationalVersion>$(Version)</InformationalVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="SD\CUDA\**" />
	  <Compile Remove="SD\Native\**" />
	  <Compile Remove="SD\Parameters\**" />
	  <EmbeddedResource Remove="SD\CUDA\**" />
	  <EmbeddedResource Remove="SD\Native\**" />
	  <EmbeddedResource Remove="SD\Parameters\**" />
	  <None Remove="SD\CUDA\**" />
	  <None Remove="SD\Native\**" />
	  <None Remove="SD\Parameters\**" />
	  <Page Remove="SD\CUDA\**" />
	  <Page Remove="SD\Native\**" />
	  <Page Remove="SD\Parameters\**" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="learn_attempt_2.cs" />
		<Compile Remove="Utility\ModelSpecific\CodeGemma.cs" />
		<Compile Remove="Utility\ModelSpecific\Mistral.cs" />
		<Compile Remove="Utility\ModelSpecific\QwenCoder.cs" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Fonts\0xProto-Regular.ttf" />
		<None Remove="Fonts\overpass-mono-bold.otf" />
		<None Remove="Fonts\overpass-mono-light.otf" />
		<None Remove="Fonts\overpass-mono-regular.otf" />
		<None Remove="Fonts\overpass-mono-semibold.otf" />
		<None Remove="learn_attempt_0.txt" />
		<None Remove="learn_attempt_1.txt" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Include="Diagnostics.bak" />
	</ItemGroup>

	<ItemGroup>
		<Content Include=".Images\iconv1.ico" />

		<!-- Exclude .pdb files from publish output -->
		<Content Update="**\*.pdb" CopyToPublishDirectory="Never" />

		<!-- Include Embed model in the executable (it's small) -->
		<Content Include="ONNX\Embed\All-MiniLM-L6-v2-ONNX\config.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="ONNX\Embed\All-MiniLM-L6-v2-ONNX\model.onnx">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="ONNX\Embed\All-MiniLM-L6-v2-ONNX\special_tokens_map.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="ONNX\Embed\All-MiniLM-L6-v2-ONNX\tokenizer.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="ONNX\Embed\All-MiniLM-L6-v2-ONNX\tokenizer_config.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="ONNX\Embed\All-MiniLM-L6-v2-ONNX\vocab.txt">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Fonts\0xProto-Regular.ttf">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Fonts\overpass-mono-bold.otf">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Fonts\overpass-mono-light.otf">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Fonts\overpass-mono-regular.otf">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Fonts\overpass-mono-semibold.otf">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>
	<ItemGroup>
		<PackageReference NoWarn="NU1900" Include="Microsoft.Data.Sqlite.Core" Version="11.0.0-preview.1.26104.118" />
		<PackageReference NoWarn="NU1900" Include="Microsoft.Extensions.AI" Version="10.7.0" />
		<PackageReference NoWarn="NU1900" Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-preview.1.26104.118" />
		<PackageReference NoWarn="NU1900" Include="Microsoft.Extensions.VectorData.Abstractions" Version="10.7.0" />
		<PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu.Windows" Version="1.26.0" />
		<PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.Cuda" Version="0.14.1" />
		<PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.Managed" Version="0.14.1" />
		<PackageReference NoWarn="NU1900" Include="Microsoft.ML.Tokenizers" Version="2.0.0" />
		<PackageReference NoWarn="NU1900" Include="Microsoft.SemanticKernel.Connectors.SqliteVec" Version="1.72.0-preview" />
		<PackageReference NoWarn="NU1900" Include="Microsoft.SemanticKernel.Core" Version="1.77.0" />
		<PackageReference NoWarn="NU1900" Include="System.Management" Version="11.0.0-preview.1.26104.118" />
	</ItemGroup>
	<ItemGroup>
		<None Update="ONNX\med-gemma-27b\config.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
		<None Update="ONNX\med-gemma-27b\genai_config.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
		<None Update="ONNX\med-gemma-27b\model.onnx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
		<None Update="ONNX\med-gemma-27b\model.onnx.data">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
		<None Update="ONNX\med-gemma-27b\special_tokens_map.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
		<None Update="ONNX\med-gemma-27b\tokenizer.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
		<None Update="ONNX\med-gemma-27b\tokenizer_config.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
		
		<None Update="ONNX\gpt-oss-20b\config.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
		<None Update="ONNX\gpt-oss-20b\genai_config.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
		<None Update="ONNX\gpt-oss-20b\model.onnx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
		<None Update="ONNX\gpt-oss-20b\model.onnx.data">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
		<None Update="ONNX\gpt-oss-20b\special_tokens_map.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
		<None Update="ONNX\gpt-oss-20b\tokenizer.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
		<None Update="ONNX\gpt-oss-20b\tokenizer_config.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
		<None Update="ONNX\Phi-4-Reasoning\config.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
		<None Update="ONNX\Phi-4-Reasoning\genai_config.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
		<None Update="ONNX\Phi-4-Reasoning\model.onnx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</None>
		<None Update="ONNX\Phi-4-Reasoning\model.onnx.data">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</None>
		<None Update="ONNX\Phi-4-Reasoning\special_tokens_map.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
		<None Update="ONNX\Phi-4-Reasoning\tokenizer.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
		<None Update="ONNX\Phi-4-Reasoning\tokenizer_config.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
		<None Update="ONNX\Phi-4-Reasoning\vocab.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
		<None Update="ONNX\SD\0nnX00Aammnpdxebr\feature_extractor\preprocessor_config.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="ONNX\SD\0nnX00Aammnpdxebr\model_index.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="ONNX\SD\0nnX00Aammnpdxebr\scheduler\scheduler_config.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="ONNX\SD\0nnX00Aammnpdxebr\text_encoder\config.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="ONNX\SD\0nnX00Aammnpdxebr\text_encoder\model.onnx">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="ONNX\SD\0nnX00Aammnpdxebr\tokenizer\merges.txt">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="ONNX\SD\0nnX00Aammnpdxebr\tokenizer\special_tokens_map.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="ONNX\SD\0nnX00Aammnpdxebr\tokenizer\tokenizer_config.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="ONNX\SD\0nnX00Aammnpdxebr\tokenizer\vocab.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="ONNX\SD\0nnX00Aammnpdxebr\unet\config.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="ONNX\SD\0nnX00Aammnpdxebr\unet\model.onnx">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="ONNX\SD\0nnX00Aammnpdxebr\vae_decoder\config.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="ONNX\SD\0nnX00Aammnpdxebr\vae_decoder\model.onnx">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="ONNX\SD\0nnX00Aammnpdxebr\vae_encoder\config.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="ONNX\SD\0nnX00Aammnpdxebr\vae_encoder\model.onnx">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="ONNX\med-gemma-27b\" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\WinFormsApp1\WinFormsApp1\Diagnostics.csproj" />
	</ItemGroup>

	<!-- Do not include native PDBs and .lib in published release (for simplicity and UX cleanliness) -->
	<Target Name="RemoveNativePDBs" AfterTargets="ComputeFilesToPublish">
		<ItemGroup>
			<ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(Extension)' == '.pdb'" />
			<ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(Extension)' == '.lib'" />
		</ItemGroup>
	</Target>
</Project>